config/routes.rb
Rails.application.routes.draw do
  root            		 'static_pages#home'
  get 'about' 		  => 'static_pages#about'
  get 'contact' 		=> 'static_pages#contact'
  get 'signup'  		=> 'users#new'
  get 'login'				=> 'sessions#new'
  post 'login'			=> 'sessions#create'
  delete 'logout'		=> 'sessions#destroy'
  resources :users  
  resources :candidates  
  resources :positions  
  resources :account_activations, only: [:edit]
  resources :password_resets, 		only: [:new, :create, :edit, :update]
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
	belongs_to :user
	has_many :applications
	has_many :positions, through: :applications

  has_attached_file :resume_pdf
  validates_attachment :resume_pdf, :content_type => { :content_type => "application/pdf" }

	before_create :create_nickname
	# before_create :create_resume_raw input must be an IO-like object or a filename
	# before_update :create_resume_raw RECURSIVE


		def create_resume_raw
			reader = PDF::Reader.new(resume_pdf.path)
			lines = reader.pages[0].text.lines.map(&:chomp)
			lines.slice!(0)
			lines_html = to_html(lines)
			update_attribute(:resume_raw, lines_html)
		end
	private

		def create_nickname
			self.nickname = "Pomegranade #{self.id}"
		end

		def to_html(lines)
			headings = %w(education experience projects languages skills)
			lines.each_with_index do |value, index| 
				if headings.include?(value.downcase)
					lines[index] = "<strong>#{value}</strong>" 
				end
			end
			lines_html = lines.map { |value| value = "<p>#{value}</p>" }
			lines_html = lines_html.keep_if { |value| value != "<p></p>" }
			lines_html.join("")
		end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

	def index
		@candidates = Candidate.paginate(page: params[:page])
	end

	def show
		@candidate = Candidate.find params[:id]
	end

	def new
		@candidate = Candidate.new
		@positions = Position.all.map { |value| [ value, value.title ] }
	end

	def create
		@candidate = Candidate.new candidate_params
		if @candidate.save
			flash[:success] = "Candidate successfully created."
			redirect_to candidate_path @candidate
		else
			flash.now[:danger] = "Candidate couldn't be saved"
			render 'new'
		end
	end

	def edit
		@candidate = Candidate.find(params[:id])
	end

	def update
		@candidate = Candidate.find(params[:id])
		if @candidate.update_attributes candidate_params
			flash[:success] = "Candidate updated"
			redirect_to @candidate
		else
			render 'edit'
		end
	end

	private

		def candidate_params
			params.require(:candidate).permit(:name, :email, :github_username, :resume_pdf)
		end

end

app/views/candidates/_candidate.html.erb
<li>
  <%= link_to candidate.nickname, candidate %>
	<% if current_user.admin? %>
		| <%= link_to "update", edit_candidate_path(candidate) %>
		| <%= link_to "delete", candidate, method: :delete,
																	data: { confirm: "Are you sure?" } %>
	<% end %>
</li>

app/views/candidates/_form.html.erb
<%= form_for(@candidate) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :github_username %>
  <%= f.text_field :github_username, class: 'form-control' %>

  <%= f.label :resume_pdf %>
  <%= f.file_field :resume_pdf, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/candidates/edit.html.erb
<% provide(:title, 'Edit candidate') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update candidate</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form' %>
	</div>
</div>

app/views/candidates/index.html.erb
<% provide(:title, 'All candidates') %>
<h1>All candidates</h1>

<%= will_paginate %>

<ul class="candidates">
  <%= render @candidates %>
</ul>

<%= will_paginate %>

app/views/candidates/new.html.erb
<% provide(:title, 'New candidate') %>
<% provide(:button_text, 'Create candidate') %>
<h1>New candidate</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/candidates/show.html.erb
<% provide(:title, @candidate.nickname) %>
<div class="row">
  <aside class="col-md-4">
    <section class="candidate_info">
      <h1>
        <%= @candidate.nickname %>
      </h1>
      <% if current_user.admin? %>
				<%= link_to "update", edit_candidate_path(@candidate) %>
				| <%= link_to "delete", @candidate, method: :delete,
																	data: { confirm: "Are you sure?" } %>
			<% end %>
			<h2>Résumé</h2>
			<% if current_user.admin? && !@candidate.resume_pdf.blank? %>
	      <p><%= link_to "Open original PDF", @candidate.resume_pdf.url, target: "_blank" %></p>
      <% end %>
			<% if !@candidate.resume_raw.blank? %>
				<div class="resume"><%= @candidate.resume_raw.html_safe %></div>				
      <% else %>
      	<p>No résumé available for this candidate yet.</p>
      <% end %>
			<h2>Applications</h2>
			<% if !@candidate.applications.blank? %>
				<% @candidate.applications.each do |application| %>
					<p><%= link_to application.position.title, application.position %></p>
					<p><strong>Status: </strong><%= application.status %></p>
				<% end %>
			<% else %>
				<p>This candidate has no applications.</p>
			<% end %>
    </section>
  </aside>
</div>